#!/bin/bash

if ! [ -x "$(command -v nvidia-docker)" ]; then
  echo 'nvidia-docker is not installed. Using CPU mode docker' >&2
  DOCKER_CMD=docker
  DOCKER_IMG="latentaiorg/public-images-limited:cpu_base_2.4"
else
  echo 'Found nvidia-docker. Using GPU mode nvidia-docker' >&2
  DOCKER_CMD=nvidia-docker
  DOCKER_IMG="latentaiorg/public-images-limited:gpu_base_2.4"
fi


mkdir -p ~/.keras
mkdir -p ~/.latentai-model-zoo

# add 	-p 6006:6006 to share port...

$DOCKER_CMD run --rm -it \
	-v `pwd`:/shared \
	-v `pwd`/../utils:/shared/utils \
	-v ~/.keras:/root/.keras \
	-v ~/.latentai-model-zoo:/root/.latentai-model-zoo \
	-w /shared \
	$DOCKER_IMG "$@"
